### PR TITLE
Added sentry

### PR DESCRIPTION
**Pull request by itaistopel**

### CODE REVIEW

**Comment by svechinsky** [comment]
We need to make sure this only logs exceptions in release builds.
We don't need development exceptions on sentry.

**Comment by itaistopel** [comment]
@svechinsky 
Wouldn't we like them both currently?

**Comment by svechinsky** [comment]
Not right now, everything we'll send to users will be packaged as a release build

**Comment by itaistopel** [comment]
> Not right now, everything we'll send to users will be packaged as a release build
@svechinsky 
Are you familiar with a way to use sentry in production only?

**Comment by svechinsky** [comment]
Not familiar but I think this might help you:
https://stackoverflow.com/questions/29901095/android-only-execute-gradle-task-on-release-build-variant#29901239

**Pull request merged**
