### PR TITLE
Feature/figma touch ups

### PR DESCRIPTION
**Pull request by itaistopel**

### CODE REVIEW

**Comment by itaistopel** [comment]
Some of the transition fragments aren't exist yet

**Comment by svechinsky** [comment]
A few comments (a side from the oximeter screen):
- Recorder audio graph should start as a flat line in a box before the user starts recording and then start chaning as the user records.
- The stepper should first appear with the medical questionnier (no before it)

**Comment by itaistopel** [comment]
image
@svechinsky

**Comment by svechinsky** [comment]
@itaistopel I found a layout issue on my phone when testing.
mic-screen-covid

**Pull request merged**
